// ══════════════════════════════════════════
// LÚMEN — Auto-Categorization Correlations
// ══════════════════════════════════════════
// Built-in correlations for Brazilian invoice descriptions.
// These run in the background and are NOT shown in the Rules tab.
// User-defined rules always take priority over these.

/**
 * Map of keyword → category.
 * Entries can be:
 *   - String → matched via case-insensitive includes()
 *   - RegExp  → matched via .test() (for precise word boundaries)
 * Longer string matches take priority (e.g., "UBER EATS" before "UBER").
 * RegExp entries are checked after all string entries.
 */
const CORRELATIONS = [
  // 🛍️ Compras Online
  ['MERCADOLIVRE', 'Compras online'],
  ['MERCADO LIVRE', 'Compras online'],
  ['MELI', 'Compras online'],
  ['MELI+', 'Compras online'],
  ['SHOPEE', 'Compras online'],
  ['AMAZON', 'Compras online'],
  ['AMZN', 'Compras online'],
  ['ALIEXPRESS', 'Compras online'],
  ['SHEIN', 'Compras online'],
  ['MAGAZINE LUIZA', 'Compras online'],
  ['MAGALU', 'Compras online'],
  ['AMERICANAS', 'Compras online'],
  ['CASAS BAHIA', 'Compras online'],
  ['SUBMARINO', 'Compras online'],
  ['NETSHOES', 'Compras online'],
  ['DAFITI', 'Compras online'],
  ['OLX', 'Compras online'],
  ['WISH', 'Compras online'],
  ['TEMU', 'Compras online'],
  ['FRETE', 'Compras online'],
  ['ENTREGA', 'Compras online'],
  ['CORREIOS', 'Compras online'],
  ['LOGGI', 'Compras online'],
  ['TOTAL EXPRESS', 'Compras online'],
  ['JADLOG', 'Compras online'],
  ['AZUL CARGO', 'Compras online'],
  ['MELHOR ENVIO', 'Compras online'],
  ['KABUM', 'Compras online'],
  ['KABUM!', 'Compras online'],
  ['PICHAU', 'Compras online'],
  ['TERABYTE', 'Compras online'],
  ['STEAM', 'Compras online'],
  ['NUUVEM', 'Compras online'],
  ['G2A', 'Compras online'],
  ['ALI', 'Compras online'],
  ['B2W', 'Compras online'],
  ['VIA VAREJO', 'Compras online'],
  ['PONTO', 'Compras online'],

  // 🍔 Alimentação
  ['IFOOD', 'Alimentação'],
  ['I FOOD', 'Alimentação'],
  ['IFD', 'Alimentação'],
  ['RAPPI', 'Alimentação'],
  ['UBER EATS', 'Alimentação'],
  ['MCDONALDS', 'Alimentação'],
  ['MC DONALDS', 'Alimentação'],
  ['MC DONALD', 'Alimentação'],
  ['BURGER KING', 'Alimentação'],
  ['SUBWAY', 'Alimentação'],
  ['HABIB', 'Alimentação'],
  ["BOB'S", 'Alimentação'],
  ['GIRAFFAS', 'Alimentação'],
  ['SPOLETO', 'Alimentação'],
  ['OUTBACK', 'Alimentação'],
  ['CACAU SHOW', 'Alimentação'],
  ['STARBUCKS', 'Alimentação'],
  ['KOPENHAGEN', 'Alimentação'],
  ['PAO DE ACUCAR', 'Alimentação'],
  ['CARREFOUR', 'Alimentação'],
  ['ATACADAO', 'Alimentação'],
  ['ASSAI', 'Alimentação'],
  ['MAKRO', 'Alimentação'],
  ['CENCOSUD', 'Alimentação'],
  ['PREZUNIC', 'Alimentação'],
  ['HORTIFRUTI', 'Alimentação'],
  ['PADARIA', 'Alimentação'],
  ['LANCHONETE', 'Alimentação'],
  ['RESTAURANTE', 'Alimentação'],
  ['PIZZARIA', 'Alimentação'],
  ['SUSHI', 'Alimentação'],
  ['ACOUGUE', 'Alimentação'],
  ['AÇOUGUE', 'Alimentação'],
  ['CONFEITARIA', 'Alimentação'],
  ['SORVETERIA', 'Alimentação'],
  ['CHURRASCARIA', 'Alimentação'],
  ['HOT DOG', 'Alimentação'],
  ['HOTDOG', 'Alimentação'],
  ['PASTELARIA', 'Alimentação'],
  ['PASTEL', 'Alimentação'],
  ['COXINHA', 'Alimentação'],
  ['DOMINOS', 'Alimentação'],
  ["DOMINO'S", 'Alimentação'],
  ['PIZZA HUT', 'Alimentação'],
  ['POPEYES', 'Alimentação'],
  ['KFC', 'Alimentação'],
  ['SEVEN ELEVEN', 'Alimentação'],
  ['7 ELEVEN', 'Alimentação'],
  ['FARMÁCIA', 'Alimentação'],
  ['DIA%', 'Alimentação'],
  ['DIA A DIA', 'Alimentação'],
  ['TONIN', 'Alimentação'],
  ['GRANADO', 'Alimentação'],
  ['ST. MARCHÉ', 'Alimentação'],
  ['SAINT MARCHÉ', 'Alimentação'],
  ['ZONA SUL', 'Alimentação'],
  ['BIG MARKET', 'Alimentação'],
  ['SEMPE', 'Alimentação'],
  ['WINE', 'Alimentação'],
  ['ADEGA', 'Alimentação'],
  ['CAFÉ', 'Alimentação'],
  ['CAFE', 'Alimentação'],
  ['COFFEE', 'Alimentação'],
  ['DELIVERY', 'Alimentação'],
  ['SABORES', 'Alimentação'],
  ['BOMBONIERE', 'Alimentação'],
  ['DOCERIA', 'Alimentação'],
  ['YAKISSOBA', 'Alimentação'],
  ['HAMBURGUER', 'Alimentação'],
  ['HAMBURGER', 'Alimentação'],
  ['ACAI', 'Alimentação'],
  ['AÇAÍ', 'Alimentação'],
  ['SUCO', 'Alimentação'],
  ['SUCOS', 'Alimentação'],
  ['BEBIDAS', 'Alimentação'],
  ['MERCANTIL', 'Alimentação'],
  ['ATACAREJO', 'Alimentação'],
  [/\b(SUPERMERCADO|MINIMERCADO|HIPERMERCADO|MERCADINHO)\b/i, 'Alimentação'],
  [/\bMERCADO\b(?!.*\b(FINANCEIRO|IMOBILIÁRIO|IMOBILIARIO|DE AÇÕES|DE ACÕES|CAPITAL|LIVRE|PAGO)\b)/i, 'Alimentação'],

  // 🚗 Transporte
  ['UBER', 'Transporte'],
  [/\b99\b|\b99TAXI\b/i, 'Transporte'],
  ['CABIFY', 'Transporte'],
  ['INDRIVER', 'Transporte'],
  ['BILHETE UNICO', 'Transporte'],
  ['BILHETE ÚNICO', 'Transporte'],
  ['METRÔ', 'Transporte'],
  ['METRO', 'Transporte'],
  ['CPTM', 'Transporte'],
  ['BILHETAGEM', 'Transporte'],
  ['DETRAN', 'Transporte'],
  ['MULTA', 'Transporte'],
  ['VELOE', 'Transporte'],
  ['CONECTCAR', 'Transporte'],
  ['SEMPARAR', 'Transporte'],
  ['MOVPASS', 'Transporte'],
  ['ECOPISTAS', 'Transporte'],
  ['ECOVIAS', 'Transporte'],
  ['ESTACIONAMENTO', 'Transporte'],
  ['PARK', 'Transporte'],
  ['PEDÁGIO', 'Transporte'],
  ['PEDAGIO', 'Transporte'],
  ['WAZE', 'Transporte'],
  ['GOOGLE MAPS', 'Transporte'],
  ['TRANSPORTE', 'Transporte'],
  ['ONIBUS', 'Transporte'],
  ['ÔNIBUS', 'Transporte'],
  ['TÁXI', 'Transporte'],
  ['TAXI', 'Transporte'],

  // ⛽ Combustível
  ['AUTO POSTO', 'Combustível'],
  [/\bPOSTO\b/i, 'Combustível'],
  ['SHELL', 'Combustível'],
  ['IPIRANGA', 'Combustível'],
  ['BR DISTRIBUIDORA', 'Combustível'],
  ['PETROBRAS', 'Combustível'],
  ['RAIZEN', 'Combustível'],
  ['ALE', 'Combustível'],
  ['VIBRA', 'Combustível'],
  ['REDE', 'Combustível'],
  ['DISLUB', 'Combustível'],
  ['RAIZEN', 'Combustível'],
  ['ELETROPOSTO', 'Combustível'],
  ['ETANOL', 'Combustível'],
  ['GASOLINA', 'Combustível'],
  ['GNV', 'Combustível'],

  // 🏦 Serviços Financeiros
  ['TARIFA', 'Tarifas bancárias'],
  ['ANUIDADE', 'Tarifas bancárias'],
  ['IOF', 'Impostos'],
  ['JUROS', 'Encargos'],
  ['SEGURO', 'Seguro'],
  ['CORRETORA', 'Investimentos'],
  ['XP INVEST', 'Investimentos'],
  ['RICO', 'Investimentos'],
  ['INTER INVEST', 'Investimentos'],
  ['NUINVEST', 'Investimentos'],
  ['BTG', 'Investimentos'],
  ['BTG PACTUAL', 'Investimentos'],
  ['CLEAR', 'Investimentos'],
  ['EASYNVEST', 'Investimentos'],
  ['TORO', 'Investimentos'],
  ['AVENUE', 'Investimentos'],
  ['CHARLES SCHWAB', 'Investimentos'],
  ['BINANCE', 'Investimentos'],
  ['CRIPTO', 'Investimentos'],
  ['BITCOIN', 'Investimentos'],
  ['MERCADOPAGO', 'Financeiro'],
  ['MERCADO PAGO', 'Financeiro'],
  ['PICPAY', 'Financeiro'],
  ['PIC PAY', 'Financeiro'],
  ['PAGSEGURO', 'Financeiro'],
  ['PAG BANK', 'Financeiro'],
  ['PAGBANK', 'Financeiro'],
  ['NUBANK', 'Financeiro'],
  ['NU BANK', 'Financeiro'],
  ['INTER', 'Financeiro'],
  ['BANCO INTER', 'Financeiro'],
  ['C6 BANK', 'Financeiro'],
  ['C6BANK', 'Financeiro'],
  ['ORIGINAL', 'Financeiro'],
  ['ITI', 'Financeiro'],
  ['ITAU', 'Financeiro'],
  ['ITAÚ', 'Financeiro'],
  ['BRADESCO', 'Financeiro'],
  ['SANTANDER', 'Financeiro'],
  ['BB ', 'Financeiro'],
  ['BANCO DO BRASIL', 'Financeiro'],
  ['CAIXA', 'Financeiro'],
  ['COOPERATIVA', 'Financeiro'],
  ['SICOOB', 'Financeiro'],
  ['SICREDI', 'Financeiro'],

  // 💊 Saúde
  ['DROGASIL', 'Saúde'],
  ['DROGARAIA', 'Saúde'],
  ['ULTRAFARMA', 'Saúde'],
  ['FARMACIA', 'Saúde'],
  ['FARMÁCIA', 'Saúde'],
  ['PAGUE MENOS', 'Saúde'],
  ['EXTRAFARMA', 'Saúde'],
  ['PANVEL', 'Saúde'],
  ['NISSEI', 'Saúde'],
  ['DROGA RAIA', 'Saúde'],
  ['RAIA', 'Saúde'],
  ['DROGASIL', 'Saúde'],
  ['LABORATORIO', 'Saúde'],
  ['LABORATÓRIO', 'Saúde'],
  ['CLINICA', 'Saúde'],
  ['CLÍNICA', 'Saúde'],
  ['HOSPITAL', 'Saúde'],
  ['ODONTO', 'Saúde'],
  ['DENTISTA', 'Saúde'],
  ['MÉDICO', 'Saúde'],
  ['MEDICO', 'Saúde'],
  ['CONSULTA', 'Saúde'],
  ['PLANO DE SAUDE', 'Saúde'],
  ['PLANO DE SAÚDE', 'Saúde'],
  ['UNIMED', 'Saúde'],
  ['AMIL', 'Saúde'],
  ['BRADESCO SAUDE', 'Saúde'],
  ['BRADESCO SAÚDE', 'Saúde'],
  ['SULAMERICA', 'Saúde'],
  ['SUL AMÉRICA', 'Saúde'],
  ['HAPVIDA', 'Saúde'],
  ['NOTREDAME', 'Saúde'],
  ['NOTRE DAME', 'Saúde'],
  ['INTERMÉDICA', 'Saúde'],
  ['GNDI', 'Saúde'],
  ['ODONTOLOGIA', 'Saúde'],
  ['ORTODONTIA', 'Saúde'],
  ['FISIOTERAPIA', 'Saúde'],
  ['PSICOLOGIA', 'Saúde'],
  ['PSICÓLOGO', 'Saúde'],
  ['PSIQUIATRA', 'Saúde'],
  ['NUTRICIONISTA', 'Saúde'],
  ['EXAME', 'Saúde'],
  ['VACINA', 'Saúde'],
  ['PRONTO SOCORRO', 'Saúde'],
  ['REMÉDIO', 'Saúde'],
  ['REMEDIO', 'Saúde'],
  ['GENÉRICO', 'Saúde'],
  ['MEDICAMENTO', 'Saúde'],

  // 🏋️ Fitness / Bem-estar
  ['SMARTFIT', 'Academia'],
  ['SMART FIT', 'Academia'],
  ['BLUEFIT', 'Academia'],
  ['BIORITMO', 'Academia'],
  ['BODYTECH', 'Academia'],
  ['ACADEMIA', 'Academia'],
  ['CROSSFIT', 'Academia'],
  ['PILATES', 'Academia'],
  ['YOGA', 'Bem-estar'],
  ['SPA', 'Bem-estar'],
  ['MASSAGEM', 'Bem-estar'],
  ['SAUNA', 'Bem-estar'],
  ['SALAO', 'Beleza'],
  ['SALÃO', 'Beleza'],
  ['BARBEARIA', 'Beleza'],
  ['CABELEIREIRO', 'Beleza'],
  ['ESTETICA', 'Beleza'],
  ['ESTÉTICA', 'Beleza'],
  ['MANICURE', 'Beleza'],
  ['PEDICURE', 'Beleza'],
  ['DESING', 'Beleza'],
  ['SOBRANCELHA', 'Beleza'],
  ['MAQUIAGEM', 'Beleza'],
  ['LASH', 'Beleza'],
  ['STUDIO', 'Beleza'],

  // 🎬 Entretenimento / Streaming
  ['NETFLIX', 'Streaming'],
  ['SPOTIFY', 'Streaming'],
  ['PRIME VIDEO', 'Streaming'],
  ['AMAZON PRIME', 'Streaming'],
  ['AMAZON MUSIC', 'Streaming'],
  ['DISNEY PLUS', 'Streaming'],
  ['DISNEY+', 'Streaming'],
  ['HBO MAX', 'Streaming'],
  ['MAX', 'Streaming'],
  ['GLOBOPLAY', 'Streaming'],
  ['GLOBO PLAY', 'Streaming'],
  ['PARAMOUNT+', 'Streaming'],
  ['PARAMOUNT PLUS', 'Streaming'],
  ['APPLE TV', 'Streaming'],
  ['APPLE MUSIC', 'Streaming'],
  ['YOUTUBE PREMIUM', 'Streaming'],
  ['YOUTUBE MUSIC', 'Streaming'],
  ['DEEZER', 'Streaming'],
  ['CRUNCHYROLL', 'Streaming'],
  ['LIONSGATE+', 'Streaming'],
  ['STAR+', 'Streaming'],
  ['CLARO TV', 'Streaming'],
  ['TELECINE', 'Streaming'],
  ['OGLE PLAY', 'Streaming'],
  ['GOOGLE PLAY', 'Streaming'],
  ['PLAYSTATION', 'Entretenimento'],
  ['PSN', 'Entretenimento'],
  ['XBOX', 'Entretenimento'],
  ['NINTENDO', 'Entretenimento'],
  ['EPIC GAMES', 'Entretenimento'],
  ['CINEMA', 'Entretenimento'],
  ['CINEMARK', 'Entretenimento'],
  ['CINEPOLIS', 'Entretenimento'],
  ['CINEPOLIS', 'Entretenimento'],
  ['UCI', 'Entretenimento'],
  ['INGRESSO', 'Entretenimento'],
  ['EVENTBRITE', 'Entretenimento'],
  ['SYMPLA', 'Entretenimento'],
  ['TICKETMASTER', 'Entretenimento'],
  ['LIVE NATION', 'Entretenimento'],
  ['SHOW', 'Entretenimento'],
  ['TEATRO', 'Entretenimento'],
  ['MUSEU', 'Entretenimento'],
  ['PARQUE', 'Entretenimento'],
  ['BOWLING', 'Entretenimento'],
  ['KARAOKÊ', 'Entretenimento'],
  ['KARAOKE', 'Entretenimento'],
  ['BALADA', 'Entretenimento'],
  ['CLUBE', 'Entretenimento'],

  // 📱 Telecomunicações
  ['VIVO', 'Telecomunicações'],
  ['CLARO', 'Telecomunicações'],
  [/\bTIM\b/i, 'Telecomunicações'],
  [/\bOI\b/i, 'Telecomunicações'],
  ['NEXTEL', 'Telecomunicações'],
  ['ALGAR', 'Telecomunicações'],
  ['SERCOMTEL', 'Telecomunicações'],
  [/\bNET\b/i, 'Telecomunicações'],
  ['SKY', 'Telecomunicações'],
  ['DIRECTV', 'Telecomunicações'],
  ['OI FIBRA', 'Telecomunicações'],
  ['VIVO FIBRA', 'Telecomunicações'],
  ['CLARO FIBRA', 'Telecomunicações'],
  ['WHATSAPP', 'Telecomunicações'],
  ['TELEFONE', 'Telecomunicações'],
  ['CELULAR', 'Telecomunicações'],

  // 🏠 Moradia / Utilidades
  ['SABESP', 'Moradia'],
  ['COPASA', 'Moradia'],
  ['SANEPAR', 'Moradia'],
  ['CEDAE', 'Moradia'],
  ['EMBASA', 'Moradia'],
  ['ENEL', 'Moradia'],
  ['CEMIG', 'Moradia'],
  ['CPFL', 'Moradia'],
  ['COELBA', 'Moradia'],
  ['ENERGISA', 'Moradia'],
  ['ELETROPAULO', 'Moradia'],
  ['ELEKTRO', 'Moradia'],
  [/\bLIGHT\b/i, 'Moradia'],
  ['COMGAS', 'Moradia'],
  ['GÁS', 'Moradia'],
  ['CONDOMINIO', 'Moradia'],
  ['CONDOMÍNIO', 'Moradia'],
  ['ALUGUEL', 'Moradia'],
  ['IPTU', 'Moradia'],
  ['SEGURO RESIDENCIAL', 'Moradia'],
  ['ÁGUA', 'Moradia'],
  ['LUZ', 'Moradia'],
  ['ENERGIA', 'Moradia'],

  // 🎓 Educação
  ['ESCOLA', 'Educação'],
  ['COLEGIO', 'Educação'],
  ['COLÉGIO', 'Educação'],
  ['UNIVERSIDADE', 'Educação'],
  ['FACULDADE', 'Educação'],
  ['ANHANGUERA', 'Educação'],
  ['UNOPAR', 'Educação'],
  ['ESTACIO', 'Educação'],
  ['UNIP', 'Educação'],
  ['UNIFESP', 'Educação'],
  ['USP', 'Educação'],
  ['KROTON', 'Educação'],
  ['COGNA', 'Educação'],
  ['CURSINHO', 'Educação'],
  ['CURSO', 'Educação'],
  ['MATERIAL ESCOLAR', 'Educação'],
  ['LIVRARIA', 'Educação'],
  ['LIVRO', 'Educação'],
  ['VESTIBULAR', 'Educação'],
  ['ENEM', 'Educação'],
  ['POS', 'Educação'],
  ['PÓS', 'Educação'],
  ['MBA', 'Educação'],
  ['UDEMY', 'Educação Online'],
  ['ALURA', 'Educação Online'],
  ['HOTMART', 'Educação Online'],
  ['EDUZZ', 'Educação Online'],
  ['KIWIFY', 'Educação Online'],
  ['DESCOMPLICA', 'Educação Online'],
  ['DOMINANDO', 'Educação Online'],
  ['SEJA DEV', 'Educação Online'],
  ['ORIGAMID', 'Educação Online'],
  ['ROCKETSEAT', 'Educação Online'],
  ['EBAC', 'Educação Online'],
  ['DIGITAL HOUSE', 'Educação Online'],
  ['COURSES', 'Educação Online'],
  ['COURSERA', 'Educação Online'],
  ['SKILL', 'Educação Online'],
  ['UDEMY', 'Educação Online'],

  // ✈️ Viagens / Hospedagem
  ['LATAM', 'Viagens'],
  [/\bGOL\b/i, 'Viagens'],
  [/\bAZUL\b/i, 'Viagens'],
  ['AVIANCA', 'Viagens'],
  ['DECOLAR', 'Viagens'],
  ['BOOKING', 'Viagens'],
  ['AIRBNB', 'Viagens'],
  ['HOTEL', 'Viagens'],
  ['POUSADA', 'Viagens'],
  ['EXPEDIA', 'Viagens'],
  ['TRIVAGO', 'Viagens'],
  ['HURB', 'Viagens'],
  ['123MILHAS', 'Viagens'],
  ['SMILES', 'Viagens'],
  ['TUDOAZUL', 'Viagens'],
  ['MULTIPLUS', 'Viagens'],
  ['VOO', 'Viagens'],
  ['PASSAGEM', 'Viagens'],
  ['HOSPEDAGEM', 'Viagens'],
  ['RESERVA', 'Viagens'],
  ['ALUGUEL CARRO', 'Viagens'],

  // 🐾 Pets
  ['PETLOVE', 'Pet'],
  ['PETZ', 'Pet'],
  ['COBASI', 'Pet'],
  ['AGROPET', 'Pet'],
  ['VETERINARIO', 'Pet'],
  ['VETERINÁRIO', 'Pet'],
  ['CLINICA VET', 'Pet'],
  ['CLÍNICA VET', 'Pet'],
  ['PET SHOP', 'Pet'],
  ['BANHO E TOSA', 'Pet'],
  ['RAÇÃO', 'Pet'],
  ['RACAO', 'Pet'],
  ['ANIMAL', 'Pet'],
  ['ADESTRAMENTO', 'Pet'],

  // 👗 Vestuário / Moda
  ['RENNER', 'Vestuário'],
  ['RIACHUELO', 'Vestuário'],
  ['MARISA', 'Vestuário'],
  ['C&A', 'Vestuário'],
  ['HERING', 'Vestuário'],
  ['ZARA', 'Vestuário'],
  [/\bFARM\b/i, 'Vestuário'],
  ['AREZZO', 'Vestuário'],
  ['RESERVA', 'Vestuário'],
  ['OSKLEN', 'Vestuário'],
  ['COLOMBO', 'Vestuário'],
  ['NIKE', 'Vestuário'],
  ['ADIDAS', 'Vestuário'],
  ['PUMA', 'Vestuário'],
  ['REEBOK', 'Vestuário'],
  ['NEW BALANCE', 'Vestuário'],
  ['CONVERSE', 'Vestuário'],
  ['VANS', 'Vestuário'],
  ['LACOSTE', 'Vestuário'],
  ['TOMMY', 'Vestuário'],
  ['CALVIN KLEIN', 'Vestuário'],
  ['LEVI\'S', 'Vestuário'],
  ['TRACKER', 'Vestuário'],
  ['MOÇA', 'Vestuário'],
  ['INTIMISSIMI', 'Vestuário'],
  ['LOUSA', 'Vestuário'],
  ['ROUPA', 'Vestuário'],
  ['CALÇADO', 'Vestuário'],
  ['SAPATO', 'Vestuário'],
  ['TENIS', 'Vestuário'],
  ['TÊNIS', 'Vestuário'],

  // 🔧 Serviços Gerais
  ['CORREIOS', 'Serviços'],
  ['CARTORIO', 'Serviços'],
  ['CARTÓRIO', 'Serviços'],
  ['DESPACHANTE', 'Serviços'],
  ['GETNINJAS', 'Serviços'],
  ['99FREELAS', 'Serviços'],
  ['FREELANCER', 'Serviços'],
  ['CHAVEIRO', 'Serviços'],
  ['ELETRICISTA', 'Serviços'],
  ['ENCANADOR', 'Serviços'],
  ['PINTOR', 'Serviços'],
  ['MARIDO DE ALUGUEL', 'Serviços'],
  ['DIARISTA', 'Serviços'],
  ['FAXINA', 'Serviços'],
  ['LAVA JATO', 'Serviços'],
  ['LAVANDERIA', 'Serviços'],
  ['TINTURARIA', 'Serviços'],

  // 🏪 Casa / Construção
  ['LEROY MERLIN', 'Casa'],
  ['TELHANORTE', 'Casa'],
  ['SODIMAC', 'Casa'],
  ['TOK STOK', 'Casa'],
  ['ETNA', 'Casa'],
  ['MOBLY', 'Casa'],
  ['KALUNGA', 'Papelaria'],
  ['CASA & VIDEO', 'Casa'],
  ['CASA E VIDEO', 'Casa'],
  ['HOME CENTER', 'Casa'],
  ['TRAMONTINA', 'Casa'],
  ['BRITO', 'Casa'],
  ['DECORAÇÃO', 'Casa'],
  ['DECORACAO', 'Casa'],
  ['MÓVEIS', 'Casa'],
  ['MOVEIS', 'Casa'],
  ['ELETRO', 'Casa'],
  ['GELADEIRA', 'Casa'],
  ['FOGÃO', 'Casa'],
  ['MAQUINA DE LAVAR', 'Casa'],
  ['AR CONDICIONADO', 'Casa'],
  ['VENTILADOR', 'Casa'],

  // 📄 Impostos / Taxas
  ['DARF', 'Impostos'],
  ['DAS', 'Impostos'],
  ['GPS', 'Impostos'],
  ['FGTS', 'Impostos'],
  ['IRPF', 'Impostos'],
  ['IMPOSTO', 'Impostos'],
  ['TAXA', 'Impostos'],
  ['RECEITA FEDERAL', 'Impostos'],
  ['SECRETARIA', 'Impostos'],

  // 🎁 Presentes / Doações
  ['PRESENT', 'Presentes'],
  ['GIFT', 'Presentes'],
  ['DOAÇÃO', 'Doações'],
  ['DOACAO', 'Doações'],
  ['VALE', 'Outros'],
  ['CREDITO', 'Outros'],
  ['CRÉDITO', 'Outros'],
  ['REEMBOLSO', 'Outros'],
  ['ESTORNO', 'Outros'],
];

// Separate string and regex entries
const STRING_CORRELATIONS = CORRELATIONS.filter(e => typeof e[0] === 'string');
const REGEX_CORRELATIONS = CORRELATIONS.filter(e => e[0] instanceof RegExp);

// Sort strings by length descending so longer matches take priority
const SORTED_STRING_CORRELATIONS = [...STRING_CORRELATIONS].sort((a, b) => b[0].length - a[0].length);

/**
 * Try to match a description against built-in correlations.
 * Returns the category string or null if no match.
 * @param {string} description - Transaction description
 */
export function matchCorrelation(description) {
  if (!description) return null;
  const desc = description.toUpperCase().trim();

  // 1. String matches (longer first)
  for (const [keyword, category] of SORTED_STRING_CORRELATIONS) {
    if (desc.includes(keyword)) {
      return category;
    }
  }

  // 2. Regex matches (precise boundaries)
  for (const [regex, category] of REGEX_CORRELATIONS) {
    if (regex.test(desc)) {
      return category;
    }
  }

  return null;
}
