import React, { useState, useEffect, useCallback } from 'react';
import { base44 } from '@/api/base44Client';
import { TrendingUp, TrendingDown, Wallet, PiggyBank, Plus, ChevronLeft, ChevronRight, AlertCircle, ArrowRight, CreditCard, Target, Calendar, Upload, Settings, ArrowUpRight, ArrowDownRight, Minus, Layers, Bell } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { formatCurrency, formatDate, filterByMonth, calcTotals, groupByCategory, getGoalProgress, getCurrentMonthKey, getMonthKey } from '@/lib/financeUtils';
import { useTransactionModal } from '@/lib/transactionModalStore';
import { CAT_COLORS, MONTH_NAMES } from '@/lib/categories';
import TransactionModal from '@/components/finance/TransactionModal';
import DashCustomizeModal from '@/components/finance/DashCustomizeModal';
import FinancialHealthScore from '@/components/finance/FinancialHealthScore';
import { useMonthNavigation } from '@/hooks/useMonthNavigation';
import { useTransactions, useBudgets, useGoals, useCards } from '@/hooks/useData';
import { cn } from '@/lib/utils';
import { Link } from 'react-router-dom';
import { lsGet, lsSet, getDashSections, getSalaryConfig, setOnboarded, fetchOnboarded, isOnboarded } from '@/lib/store';
import { getCategoryIcon } from '@/lib/categories';
import { checkDueDateNotifications } from '@/lib/notifications';
import { KpiCard, getDelta } from '@/components/dashboard/KpiCard';
import HeroBalance from '@/components/dashboard/HeroBalance';
import StatusLine from '@/components/dashboard/StatusLine';
import OnboardingModal from '@/components/dashboard/OnboardingModal';
import ChartsSection from '@/components/dashboard/ChartsSection';
import CategoryBreakdown from '@/components/dashboard/CategoryBreakdown';
import GoalsSection from '@/components/dashboard/GoalsSection';

// ═══ Onboarding, KPI, and helpers moved to src/components/dashboard/ ═══

export default function Dashboard() {
  const { month: currentMonth, year: currentYear, navigate } = useMonthNavigation();
  const [showModal, setShowModal] = useState(false);
  const [defaultType, setDefaultType] = useState('expense');
  const [showOnboarding, setShowOnboarding] = useState(false);
  const [showCustomize, setShowCustomize] = useState(false);
  const [dashSections, setDashSections] = useState(getDashSections());
  const [showKpiResumo, setShowKpiResumo] = useState(() => {
    if (typeof window !== 'undefined' && window.innerWidth >= 1024) return true;
    return false;
  });

  useEffect(() => {
    let cancelled = false;

    async function checkOnboarding() {
      // 1. Verifica localStorage imediatamente
      if (isOnboarded()) {
        checkDueDateNotifications();
        return;
      }
      // 2. Nao esta no localStorage — busca na nuvem (pode ter completado em outro dispositivo)
      const cloudResult = await fetchOnboarded();
      if (cancelled) return;
      if (cloudResult && cloudResult !== 'false') {
        checkDueDateNotifications();
        return;
      }
      // 3. Realmente nao onboardou — exibe apos delay
      const timer = setTimeout(() => {
        if (!cancelled) setShowOnboarding(true);
      }, 800);
      return () => clearTimeout(timer);
    }

    checkOnboarding();
    return () => { cancelled = true; };
  }, []);

  const { data: transactions = [], refetch: refetchTx } = useTransactions();
  const { data: goals = [] } = useGoals();
  const { data: budgets = [] } = useBudgets();
  const { data: cards = [] } = useCards();

  useEffect(() => {
    if (transactions.length > 0) {
      // Guard: mark current month as handled to avoid duplicate cron triggers client-side.
      // Actual generation is handled by the backend generateRecurring cron.
      const currentKey = getCurrentMonthKey();
      const lastGen = lsGet('lastRecurringGen', '');
      if (lastGen !== currentKey) {
        lsSet('lastRecurringGen', currentKey);
      }
    }
  }, [transactions.length]);

  // Budget alerts are generated by Layout's NotificationCenter (single source of truth)

  useEffect(() => {
    const unsub = useTransactionModal.subscribe(({ isOpen, defaultType }) => {
      if (isOpen) {
        setDefaultType(defaultType);
        setShowModal(true);
      }
    });
    return unsub;
  }, []);

  const monthTx = React.useMemo(() => filterByMonth(transactions, currentYear, currentMonth), [transactions, currentYear, currentMonth]);
  const totals = React.useMemo(() => calcTotals(monthTx), [monthTx]);
  const expensesByCategory = React.useMemo(
    () => groupByCategory(monthTx.filter(t => t.type === 'expense')),
    [monthTx]
  );

  // Previous month for comparison
  const prevMonthData = React.useMemo(() => {
    let pm = currentMonth - 1, py = currentYear;
    if (pm < 0) { pm = 11; py--; }
    const prevTx = filterByMonth(transactions, py, pm);
    return { prevTx, prevTotals: calcTotals(prevTx) };
  }, [transactions, currentMonth, currentYear]);
  const { prevTx: prevMonthTx, prevTotals } = prevMonthData;

  const pieData = React.useMemo(() => expensesByCategory.map(([cat, val]) => ({
    name: cat, value: val, color: CAT_COLORS[cat] || '#94a3b8'
  })), [expensesByCategory]);

  const MAX_PIE_SLICES = 6;

  const processedPieData = React.useMemo(() => {
    if (!pieData || pieData.length === 0) return [];
    if (pieData.length <= MAX_PIE_SLICES) return pieData;
    const sorted = [...pieData].sort((a, b) => b.value - a.value);
    const top = sorted.slice(0, MAX_PIE_SLICES);
    const rest = sorted.slice(MAX_PIE_SLICES);
    const othersValue = rest.reduce((sum, d) => sum + d.value, 0);
    return [...top, { name: 'Outros', value: othersValue, color: '#94a3b8' }];
  }, [pieData]);

  const barData = React.useMemo(() => {
    const data = [];
    for (let i = 5; i >= 0; i--) {
      let m = currentMonth - i, y = currentYear;
      if (m < 0) { m += 12; y -= 1; }
      const txs = filterByMonth(transactions, y, m);
      const t = calcTotals(txs);
      data.push({ name: MONTH_NAMES[m].slice(0, 3), income: t.income, expense: t.expense });
    }
    return data;
  }, [transactions, currentMonth, currentYear]);

  const monthBudgets = React.useMemo(() => {
    const key = getMonthKey(currentYear, currentMonth);
    return budgets.filter(b => b.month === key);
  }, [budgets, currentYear, currentMonth]);

  const handleSave = async (data) => {
    await base44.entities.Transaction.create(data);
    refetchTx();
    setShowModal(false);
  };

  const alerts = React.useMemo(() => monthBudgets.filter(b => {
    const spent = monthTx.filter(t => t.type === 'expense' && t.category === b.category).reduce((s, t) => s + t.value, 0);
    return spent > b.limit;
  }), [monthBudgets, monthTx]);

  // Section visibility helper
  const isSectionVisible = (id) => {
    const s = dashSections.find(s => s.id === id);
    return s ? s.visible : true;
  };

  // ── Installment transactions ──
  const installmentTx = React.useMemo(() => monthTx.filter(t => t.isInstallment), [monthTx]);
  const installmentTotal = React.useMemo(() => installmentTx.reduce((s, t) => s + Math.abs(t.value), 0), [installmentTx]);

  // ── Upcoming due dates ──
  const salaryConfig = getSalaryConfig();
  const upcomingItems = React.useMemo(() => {
    const today = new Date();
    const items = [];
    cards.forEach(c => {
      const diff = c.dueDay - today.getDate();
      if (diff >= 0 && diff <= 7) {
        const cardTotal = monthTx.filter(t => t.cardId === c.id && t.type === 'expense').reduce((s, t) => s + t.value, 0);
        items.push({ label: `Fatura ${c.name}`, date: `dia ${c.dueDay}`, value: cardTotal, color: 'text-red-500', icon: CreditCard });
      }
    });
    if (salaryConfig.autoGenerate || salaryConfig.value > 0) {
      const salaryDiff = salaryConfig.day - today.getDate();
      if (salaryDiff >= 0 && salaryDiff <= 7) {
        items.push({ label: 'Salário', date: `dia ${salaryConfig.day}`, value: salaryConfig.value, color: 'text-emerald-500', icon: Wallet });
      }
    }
    return items;
  }, [cards, monthTx, salaryConfig]);

  // ── Patrimônio total (saldo acumulado de todos os meses) ──
  const allTotals = React.useMemo(() => calcTotals(transactions), [transactions]);
  const patrimonio = allTotals.balance;

  // ── Forecast (simple: avg of last 3 months) ──
  const { avgIncome, avgExpense } = React.useMemo(() => {
    const data = [];
    for (let i = 2; i >= 0; i--) {
      let m = currentMonth - 1 - i, y = currentYear;
      if (m < 0) { m += 12; y -= 1; }
      const txs = filterByMonth(transactions, y, m);
      data.push(calcTotals(txs));
    }
    return {
      avgIncome: data.reduce((s, t) => s + t.income, 0) / 3,
      avgExpense: data.reduce((s, t) => s + t.expense, 0) / 3,
    };
  }, [transactions, currentMonth, currentYear]);

  // Render sections in order
  const orderedSections = dashSections.filter(s => s.visible);

  const renderSection = (sectionId) => {
    switch (sectionId) {
      case 'resumo': return renderResumo();
      case 'graficos': return renderGraficos();
      case 'gastos': return renderGastos();
      case 'metas': return renderMetas();
      case 'parcelas': return renderParcelas();
      case 'planejado': return renderPlanejado();
      case 'previsao': return renderPrevisao();
      case 'vencimentos': return renderVencimentos();
      case 'patrimonio': return renderPatrimonio();
      case 'tendencia': return renderTendencia();
      default: return null;
    }
  };

  // ═══ Section Renderers ═══

  function renderResumo() {
    return (
      <div key="resumo">
        {/* Collapsible header */}
        <button
          onClick={() => setShowKpiResumo(v => !v)}
          className="flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground transition-colors mb-3 w-full"
        >
          <ChevronRight size={14} className={cn('transition-transform duration-200', showKpiResumo && 'rotate-90')} />
          Resumo do Mês
        </button>

        {showKpiResumo && (
          <>
            {/* Mobile: horizontal scroll carousel */}
            <div className="flex lg:hidden gap-3 overflow-x-auto pb-1 -mx-4 px-4 snap-x snap-mandatory scrollbar-hide animate-fade-in">
              <div className="shrink-0 w-44 snap-start">
                <KpiCard label="Receitas" value={formatCurrency(totals.income)} icon={TrendingUp} variant="income"
                  delta={getDelta(totals.income, prevTotals.income)} deltaLabel="vs mês ant." />
              </div>
              <div className="shrink-0 w-44 snap-start">
                <KpiCard label="Despesas" value={formatCurrency(totals.expense)} icon={TrendingDown} variant="expense"
                  delta={getDelta(totals.expense, prevTotals.expense)} deltaLabel="vs mês ant." />
              </div>
              <div className="shrink-0 w-44 snap-start">
                <KpiCard label="Saldo" value={formatCurrency(totals.balance)} icon={Wallet} variant="balance"
                  delta={getDelta(totals.balance, prevTotals.balance)} deltaLabel="vs mês ant." />
              </div>
              <div className="shrink-0 w-44 snap-start">
                <KpiCard label="Investido" value={formatCurrency(totals.investment)} icon={PiggyBank} variant="investment" />
              </div>
            </div>

            {/* Desktop: 4-column grid */}
            <div className="hidden lg:grid grid-cols-4 gap-3 animate-fade-in">
              <KpiCard label="Receitas" value={formatCurrency(totals.income)} icon={TrendingUp} variant="income"
                delta={getDelta(totals.income, prevTotals.income)} deltaLabel="vs mês ant." />
              <KpiCard label="Despesas" value={formatCurrency(totals.expense)} icon={TrendingDown} variant="expense"
                delta={getDelta(totals.expense, prevTotals.expense)} deltaLabel="vs mês ant." />
              <KpiCard label="Saldo" value={formatCurrency(totals.balance)} icon={Wallet} variant="balance"
                delta={getDelta(totals.balance, prevTotals.balance)} deltaLabel="vs mês ant." />
              <KpiCard label="Investido" value={formatCurrency(totals.investment)} icon={PiggyBank} variant="investment" />
            </div>
          </>
        )}

        <div className="mt-3 animate-fade-in" style={{ animationDelay: '0.05s' }}>
          <FinancialHealthScore
            transactions={transactions}
            budgets={budgets}
            goals={goals}
            month={currentMonth}
            year={currentYear}
          />
        </div>
      </div>
    );
  }

  function renderGraficos() {
    return <ChartsSection key="graficos" barData={barData} processedPieData={processedPieData} />;
  }

  function renderGastos() {
    return (
      <div key="gastos" className="animate-fade-in-up" style={{ animationDelay: '0.15s' }}>
        <CategoryBreakdown expensesByCategory={expensesByCategory} totals={totals} />
      </div>
    );
  }

  function renderMetas() {
    return (
      <div key="metas" className="animate-fade-in-up" style={{ animationDelay: '0.2s' }}>
        <GoalsSection goals={goals} transactions={transactions} />
      </div>
    );
  }

  function renderParcelas() {
    if (installmentTx.length === 0) return null;
    return (
      <div key="parcelas" className="animate-fade-in-up" style={{ animationDelay: '0.22s' }}>
        <Card className="border-0 shadow-card overflow-hidden">
          <CardHeader className="pb-3 border-b border-border/40">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-semibold flex items-center gap-2">
                <div className="w-1.5 h-4 rounded-full bg-pink-500" /> Parcelas Ativas
              </CardTitle>
              <span className="text-sm font-bold text-red-500 tabular-nums">{formatCurrency(installmentTotal)}</span>
            </div>
          </CardHeader>
          <CardContent className="pt-4 space-y-2">
            {installmentTx.slice(0, 5).map(t => (
              <div key={t.id} className="flex items-center justify-between p-2 -mx-2 rounded hover:bg-muted/50 transition-colors">
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium truncate">{t.description}</p>
                  <p className="text-xs text-muted-foreground">
                    <Badge variant="outline" className="text-[10px] py-0 px-1.5 bg-blue-50 border-blue-200 text-blue-600 mr-1">
                      {t.installmentCurrent}/{t.installmentCount}
                    </Badge>
                    {formatDate(t.date)}
                  </p>
                </div>
                <span className="text-sm font-bold text-red-500 tabular-nums shrink-0">{formatCurrency(Math.abs(t.value))}</span>
              </div>
            ))}
            {installmentTx.length > 5 && (
              <Link to="/transactions" className="block text-center text-xs text-primary font-medium hover:underline mt-2">
                Ver todas ({installmentTx.length})
              </Link>
            )}
          </CardContent>
        </Card>
      </div>
    );
  }

  function renderPlanejado() {
    if (monthBudgets.length === 0) return null;
    return (
      <div key="planejado" className="animate-fade-in-up" style={{ animationDelay: '0.25s' }}>
        <Card className="border-0 shadow-card overflow-hidden">
          <CardHeader className="pb-3 border-b border-border/40">
            <CardTitle className="text-sm font-semibold flex items-center gap-2">
              <div className="w-1.5 h-4 rounded-full bg-amber-500" /> Planejado vs Real
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4 space-y-3">
            {monthBudgets.map(b => {
              const spent = monthTx.filter(t => t.type === 'expense' && t.category === b.category).reduce((s, t) => s + t.value, 0);
              const pct = b.limit > 0 ? Math.min(100, (spent / b.limit) * 100) : 0;
              const over = spent > b.limit;
              return (
                <div key={b.id}>
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-sm font-medium">{getCategoryIcon(b.category)} {b.category}</span>
                    <span className={cn("text-xs font-semibold", over ? 'text-red-500' : 'text-muted-foreground')}>
                      {formatCurrency(spent)} / {formatCurrency(b.limit)}
                    </span>
                  </div>
                  <div className="h-2 bg-muted rounded-full overflow-hidden">
                    <div className={cn("h-full rounded-full transition-all duration-500", over ? 'bg-red-500' : 'bg-primary')} style={{ width: `${pct}%` }} />
                  </div>
                </div>
              );
            })}
          </CardContent>
        </Card>
      </div>
    );
  }

  function renderPrevisao() {
    return (
      <div key="previsao" className="animate-fade-in-up" style={{ animationDelay: '0.28s' }}>
        <Card className="border-0 shadow-card overflow-hidden">
          <CardHeader className="pb-3 border-b border-border/40">
            <CardTitle className="text-sm font-semibold flex items-center gap-2">
              <div className="w-1.5 h-4 rounded-full bg-cyan-500" /> Previsão Próximo Mês
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
              <div>
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold">Receita Prev.</p>
                <p className="text-lg font-bold text-emerald-600 tabular-nums mt-1">{formatCurrency(avgIncome)}</p>
              </div>
              <div>
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold">Despesa Prev.</p>
                <p className="text-lg font-bold text-red-500 tabular-nums mt-1">{formatCurrency(avgExpense)}</p>
              </div>
              <div>
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold">Saldo Prev.</p>
                <p className={cn("text-lg font-bold tabular-nums mt-1", avgIncome - avgExpense >= 0 ? 'text-emerald-600' : 'text-red-500')}>
                  {formatCurrency(avgIncome - avgExpense)}
                </p>
              </div>
            </div>
            <p className="text-[10px] text-muted-foreground mt-3">Baseado na média dos últimos 3 meses</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  function renderVencimentos() {
    if (upcomingItems.length === 0) return null;
    return (
      <div key="vencimentos" className="animate-fade-in-up" style={{ animationDelay: '0.3s' }}>
        <Card className="border-0 shadow-card overflow-hidden">
          <CardHeader className="pb-3 border-b border-border/40">
            <CardTitle className="text-sm font-semibold flex items-center gap-2">
              <div className="w-1.5 h-4 rounded-full bg-orange-500" /> Próximos Vencimentos
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4 space-y-2">
            {upcomingItems.map((item, i) => (
              <div key={i} className="flex items-center gap-3 p-2 -mx-2 rounded hover:bg-muted/50 transition-colors">
                <div className="w-9 h-9 rounded flex items-center justify-center bg-muted">
                  <item.icon size={16} className={item.color} />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium">{item.label}</p>
                  <p className="text-xs text-muted-foreground">{item.date}</p>
                </div>
                <span className={cn("text-sm font-bold tabular-nums", item.color)}>{formatCurrency(item.value)}</span>
              </div>
            ))}
          </CardContent>
        </Card>
      </div>
    );
  }

  function renderPatrimonio() {
    return (
      <div key="patrimonio" className="animate-fade-in-up" style={{ animationDelay: '0.32s' }}>
        <Card className="border-0 shadow-card overflow-hidden">
          <CardHeader className="pb-3 border-b border-border/40">
            <CardTitle className="text-sm font-semibold flex items-center gap-2">
              <div className="w-1.5 h-4 rounded-full bg-indigo-500" /> Patrimônio Total
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded bg-indigo-100">
                <PiggyBank size={24} className="text-indigo-600" />
              </div>
              <div>
                <p className={cn("text-2xl font-bold tabular-nums", patrimonio >= 0 ? 'text-foreground' : 'text-red-500')}>
                  {formatCurrency(patrimonio)}
                </p>
                <p className="text-xs text-muted-foreground mt-0.5">Saldo acumulado total (receitas − despesas − investimentos)</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  function renderTendencia() {
    return (
      <div key="tendencia" className="animate-fade-in-up" style={{ animationDelay: '0.34s' }}>
        <Card className="border-0 shadow-card overflow-hidden">
          <CardHeader className="pb-3 border-b border-border/40">
            <CardTitle className="text-sm font-semibold flex items-center gap-2">
              <div className="w-1.5 h-4 rounded-full bg-teal-500" /> Tendência vs Mês Anterior
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
              <div className="text-center">
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold mb-2">Receitas</p>
                <div className="flex items-center justify-center gap-1">
                  {getDelta(totals.income, prevTotals.income) > 0 ? (
                    <ArrowUpRight size={16} className="text-emerald-500" />
                  ) : getDelta(totals.income, prevTotals.income) < 0 ? (
                    <ArrowDownRight size={16} className="text-red-500" />
                  ) : <Minus size={16} className="text-muted-foreground" />}
                  <span className={cn("text-lg font-bold", getDelta(totals.income, prevTotals.income) >= 0 ? 'text-emerald-600' : 'text-red-500')}>
                    {getDelta(totals.income, prevTotals.income).toFixed(1)}%
                  </span>
                </div>
                <p className="text-[10px] text-muted-foreground mt-1">{formatCurrency(totals.income)} vs {formatCurrency(prevTotals.income)}</p>
              </div>
              <div className="text-center">
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold mb-2">Despesas</p>
                <div className="flex items-center justify-center gap-1">
                  {getDelta(totals.expense, prevTotals.expense) > 0 ? (
                    <ArrowUpRight size={16} className="text-red-500" />
                  ) : getDelta(totals.expense, prevTotals.expense) < 0 ? (
                    <ArrowDownRight size={16} className="text-emerald-500" />
                  ) : <Minus size={16} className="text-muted-foreground" />}
                  <span className={cn("text-lg font-bold", getDelta(totals.expense, prevTotals.expense) <= 0 ? 'text-emerald-600' : 'text-red-500')}>
                    {getDelta(totals.expense, prevTotals.expense).toFixed(1)}%
                  </span>
                </div>
                <p className="text-[10px] text-muted-foreground mt-1">{formatCurrency(totals.expense)} vs {formatCurrency(prevTotals.expense)}</p>
              </div>
              <div className="text-center">
                <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold mb-2">Saldo</p>
                <div className="flex items-center justify-center gap-1">
                  {getDelta(totals.balance, prevTotals.balance) > 0 ? (
                    <ArrowUpRight size={16} className="text-emerald-500" />
                  ) : getDelta(totals.balance, prevTotals.balance) < 0 ? (
                    <ArrowDownRight size={16} className="text-red-500" />
                  ) : <Minus size={16} className="text-muted-foreground" />}
                  <span className={cn("text-lg font-bold", getDelta(totals.balance, prevTotals.balance) >= 0 ? 'text-emerald-600' : 'text-red-500')}>
                    {getDelta(totals.balance, prevTotals.balance).toFixed(1)}%
                  </span>
                </div>
                <p className="text-[10px] text-muted-foreground mt-1">{formatCurrency(totals.balance)} vs {formatCurrency(prevTotals.balance)}</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="p-4 lg:p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold font-display">Dashboard</h1>
          <p className="text-muted-foreground text-sm mt-0.5">Visão geral das suas finanças</p>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1 bg-card border rounded px-2 py-1">
            <button onClick={() => navigate(-1)} className="p-1 hover:bg-muted rounded" aria-label="Mês anterior"><ChevronLeft size={14} /></button>
            <span className="text-sm font-medium px-2 min-w-[120px] text-center">
              {MONTH_NAMES[currentMonth]} {currentYear}
            </span>
            <button onClick={() => navigate(1)} className="p-1 hover:bg-muted rounded" aria-label="Próximo mês"><ChevronRight size={14} /></button>
          </div>
          <Button size="sm" variant="outline" onClick={() => setShowCustomize(true)}>
            <Settings size={14} className="mr-1" /> Personalizar
          </Button>
          <Button size="sm" onClick={() => setShowModal(true)}>
            <Plus size={14} className="mr-1" /> Novo
          </Button>
        </div>
      </div>

      {/* Alerts */}
      {alerts.length > 0 && (
        <div className="flex items-center gap-2 p-3 bg-red-50 border border-red-200 rounded text-red-700 text-sm">
          <AlertCircle size={16} />
          <span>{alerts.length} orçamento(s) ultrapassado(s): {alerts.map(a => a.category).join(', ')}</span>
        </div>
      )}

      {/* Hero Balance — editorial headline number */}
      <HeroBalance balance={totals.balance} income={totals.income} expense={totals.expense} />

      {/* Status Line — compact indicators */}
      <StatusLine
        budgets={budgets}
        monthBudgets={monthBudgets}
        goals={goals}
        upcomingItems={upcomingItems}
        monthTx={monthTx}
      />

      {/* Dynamic sections */}
      {orderedSections.map((s, i) => (
        <div key={s.id}>
          {renderSection(s.id)}
        </div>
      ))}

      {/* Recent transactions (always shown at bottom) */}
      <Card className="border-0 shadow-card overflow-hidden animate-fade-in-up" style={{ animationDelay: '0.35s' }}>
        <CardHeader className="pb-3 border-b border-border/40">
          <CardTitle className="text-sm font-semibold flex items-center gap-2">
            <div className="w-1.5 h-4 rounded-full bg-emerald-500" /> Últimas Transações
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 pt-4">
          {monthTx.length === 0 ? (
            <p className="text-muted-foreground text-sm">Sem transações neste mês</p>
          ) : (
            monthTx.slice(0, 5).map(t => (
              <div key={t.id} className="flex items-center gap-3 p-2 -mx-2 rounded hover:bg-muted/50 transition-colors">
                <div className={cn(
                  "w-9 h-9 rounded flex items-center justify-center text-xs font-bold shrink-0 shadow-sm",
                  t.type === 'income' ? 'gradient-emerald text-emerald-700' :
                  t.type === 'expense' ? 'gradient-red text-red-700' : 'gradient-violet text-amber-700'
                )}>
                  {(t.description || '?')[0].toUpperCase()}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium truncate">{t.description}</p>
                  <p className="text-xs text-muted-foreground">{t.category ? <>{getCategoryIcon(t.category)} {t.category}</> : '—'}</p>
                </div>
                <span className={cn(
                  "text-sm font-semibold shrink-0",
                  t.type === 'income' ? 'text-emerald-600' : t.type === 'expense' ? 'text-red-500' : 'text-amber-600'
                )}>
                  {t.type !== 'income' ? '-' : '+'}{formatCurrency(t.value)}
                </span>
              </div>
            ))
          )}
        </CardContent>
      </Card>

      <TransactionModal open={showModal} onClose={() => setShowModal(false)} onSave={handleSave} goals={goals} defaultType={defaultType} />
      <OnboardingModal open={showOnboarding} onClose={() => setShowOnboarding(false)} />
      <DashCustomizeModal open={showCustomize} onClose={() => setShowCustomize(false)} onUpdate={(s) => setDashSections(s)} />
    </div>
  );
}
